# Generated by Django 3.2 on 2021-04-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_game_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='detailed_description',
            field=models.TextField(default=''),
        ),
    ]
