# Generated by Django 3.2 on 2021-05-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_item_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_login',
            field=models.CharField(default='account_login', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='item_password',
            field=models.CharField(default='password123', max_length=100),
        ),
    ]
