# Generated by Django 3.2 on 2021-05-15 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='seller',
        ),
    ]
