# Generated by Django 3.2 on 2021-05-20 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_item_sellerfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sellerFK',
        ),
    ]
